### ISSUE TITLE
Creating a maven proxy repository returns 404

### ISSUE THREAD

**Issue by c4rlier** [datadrivers/terraform-provider-nexus#28]
Hi,

Trying to create a maven proxy repository returns a 404. I tried to create multiple different maven proxy repositories, but all of them return 404. Below is one example.

```
resource "nexus_repository" "repo1_proxy" {
  name   = "repo1-proxy"
  format = "maven2"
  type   = "proxy"

  maven {
    version_policy = "RELEASE"
    layout_policy = "STRICT"
  }

  negative_cache {
    enabled = true
    ttl     = 1440
  }

  proxy {
    remote_url  = "https://repo1.maven.org/maven2"
  }

  storage {
    blob_store_name                = nexus_blobstore.s3.name
    strict_content_type_validation = true
  }
}
```

**Comment by Nosmoht** [comment]
Hi @c4rlier ,

we already identified the issue and will fix it soon.

**Comment by Nosmoht** [comment]
Hi @c4rlier ,

that was an issue within the used go-nexus-client library that is fixed in https://github.com/datadrivers/go-nexus-client/releases/tag/v0.8.2. We will release a new Terraform provider soon, using the new client library. That should fix the issue.

**Comment by Nosmoht** [comment]
Hi @c4rlier ,

this should be fixed with https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.4.1.

**Comment by Michenux** [comment]
I'm using version 1.6.1 and it is not fixed.

```
Error: could not create repository 'my-mvn-group': HTTP: 404, 

  on nexus.tf line 56, in resource "nexus_repository" "maven_group":
  56: resource "nexus_repository" "maven_group" {
```

terraform providers
```
.
├── provider.aws >= 2.60.0
└── provider.nexus >= 1.6.0
````

**Comment by ruedigerblock** [comment]
Moin @Michenux,
may I ask for the corresponding TF code, thus I can compare ?

**Comment by Michenux** [comment]
Yes

```
resource "nexus_repository" "maven_group" {
  name   = "${var.project_name}-mvn-group"
  format = "maven2"
  type   = "group"
  online = true

  group {
    member_names = [nexus_repository.maven_hosted.name, "maven-public"]
  }

  storage {
    blob_store_name                = nexus_blobstore.aws.name
    strict_content_type_validation = true
  }
}
```

In fact, there is no endpoint in API to create a maven group.
It is fixed in Nexus 3.24, but not yet released.
https://issues.sonatype.org/browse/NEXUS-23080

**Comment by ruedigerblock** [comment]
I see it know. Thus, we'll have to wait for 3.24 to come out. :-(

**Comment by Michenux** [comment]
3.24.0 released:
https://help.sonatype.com/repomanager3/release-notes#ReleaseNotes-NexusRepositoryManager3.24.0

**Comment by Nosmoht** [comment]
Hi @Michenux ,

thanks for the information. I'll start with the implementation.

**Comment by Nosmoht** [comment]
Hi @Michenux ,

i've just tested with provider [v1.7.0](https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.7.0) and it works already. So please use this version.

**Comment by fog1985** [comment]
Cool. I have just faced this issue as well. I needed to create maven groups. And could not find them implemented. Now I see that it's up to Nexus API. It has not been implemented at all.

**Comment by Nosmoht** [comment]
It's implemented in Nexus 3.24.0 and supported by provider [v1.7.0](https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v1.7.0)

**Comment by android-leha** [comment]
Probably this can be closed

**Comment by Michenux** [comment]
Yes, you can.
Thanks for your work 👍
